import { describe, expect, it } from "vitest";
import { generateTeamSummary } from "@/lib/team/summary";
import type { AgentDefinition, TeamSnapshot } from "@/lib/types";

function makeAgent(
  name: string,
  mode: AgentDefinition["mode"],
  extra: Partial<AgentDefinition> = {},
): AgentDefinition {
  return {
    name,
    mode,
    source: name === "build" || name === "plan" ? "builtin" : "file",
    builtin: name === "build" || name === "plan",
    description: extra.description || `Description for ${name}`,
    prompt: "",
    model: extra.model,
    options: {},
    permission: extra.permission || {},
    extra: {},
    hidden: extra.hidden || false,
  };
}

function baseSnapshot(overrides?: Partial<TeamSnapshot>): TeamSnapshot {
  return {
    agents: [
      makeAgent("build", "primary"),
      makeAgent("plan", "primary"),
      makeAgent("reviewer", "subagent"),
    ],
    skills: [
      { name: "typescript", description: "TS expertise", license: undefined, compatibility: undefined, metadata: {}, body: "" },
      { name: "docker", description: "Docker expertise", license: undefined, compatibility: undefined, metadata: {}, body: "" },
    ],
    mcps: [
      { name: "github", type: "remote", enabled: true, command: [], environment: {}, headers: {}, url: "http://localhost" },
    ],
    providers: [],
    globalPermission: {},
    defaultAgent: "build",
    layout: { version: 2, views: {} },
    metadata: { version: 2 },
    ...overrides,
  };
}

describe("generateTeamSummary", () => {
  describe("structure générale", () => {
    it("commence par le titre et la note", () => {
      const md = generateTeamSummary(baseSnapshot());
      expect(md).toContain("## OpenCode team");
      expect(md).toContain("> Generated by OpenCode Team Studio");
    });

    it("place les agents principaux avant les sous-agents", () => {
      const md = generateTeamSummary(baseSnapshot());
      const buildIndex = md.indexOf("### `build`");
      const planIndex = md.indexOf("### `plan`");
      const reviewerIndex = md.indexOf("### `reviewer`");
      expect(buildIndex).toBeLessThan(reviewerIndex);
      expect(planIndex).toBeLessThan(reviewerIndex);
    });

    it("trie les agents de même type par nom", () => {
      const md = generateTeamSummary(baseSnapshot());
      const buildIndex = md.indexOf("### `build`");
      const planIndex = md.indexOf("### `plan`");
      expect(buildIndex).toBeLessThan(planIndex);
    });

    it("exclut les agents cachés", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary"),
          makeAgent("hidden-agent", "subagent", { hidden: true }),
        ],
      });
      const md = generateTeamSummary(snap);
      expect(md).not.toContain("hidden-agent");
    });

    it("est déterministe", () => {
      const snap = baseSnapshot();
      const a = generateTeamSummary(snap);
      const b = generateTeamSummary(snap);
      expect(a).toBe(b);
    });
  });

  describe("contenu par agent", () => {
    it("affiche le type de l'agent", () => {
      const md = generateTeamSummary(baseSnapshot());
      expect(md).toContain("- Type: primary");
      expect(md).toContain("- Type: subagent");
    });

    it("affiche le modèle quand il est présent", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary", { model: "anthropic/claude-sonnet" }),
          makeAgent("reviewer", "subagent"),
        ],
      });
      const md = generateTeamSummary(snap);
      expect(md).toContain("- Model: `anthropic/claude-sonnet`");
      expect(md).not.match(/reviewer[\s\S]*?- Model:/);
    });

    it("omet la ligne Model quand elle n'existe pas", () => {
      const snap = baseSnapshot({
        agents: [makeAgent("build", "primary")],
      });
      const md = generateTeamSummary(snap);
      const buildBlock = md.slice(md.indexOf("### `build`"));
      const nextSection = buildBlock.indexOf("### `", 1);
      const block = nextSection > 0 ? buildBlock.slice(0, nextSection) : buildBlock;
      expect(block).not.toContain("- Model:");
    });

    it("n'affiche pas de lignes avec 'none'", () => {
      const snap = baseSnapshot({
        agents: [makeAgent("build", "primary")],
        skills: [],
        mcps: [],
      });
      const md = generateTeamSummary(snap);
      expect(md).not.toContain("none");
    });
  });

  describe("délégations", () => {
    it("liste les agents vers lesquels l'agent délègue", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary", {
            permission: { task: { reviewer: "allow" } },
          }),
          makeAgent("reviewer", "subagent"),
        ],
      });
      const md = generateTeamSummary(snap);
      const buildBlock = md.slice(md.indexOf("### `build`"));
      const nextSection = buildBlock.indexOf("### `", 1);
      const block = nextSection > 0 ? buildBlock.slice(0, nextSection) : buildBlock;
      expect(block).toContain("Delegates to:");
      expect(block).toContain("`reviewer`");
    });

    it("liste les agents qui appellent cet agent", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary", {
            permission: { task: { reviewer: "allow" } },
          }),
          makeAgent("reviewer", "subagent"),
        ],
      });
      const md = generateTeamSummary(snap);
      const reviewerBlock = md.slice(md.indexOf("### `reviewer`"));
      const nextSection = reviewerBlock.indexOf("### `", 1);
      const block = nextSection > 0 ? reviewerBlock.slice(0, nextSection) : reviewerBlock;
      expect(block).toContain("Called by:");
      expect(block).toContain("`build`");
    });
  });

  describe("skills et MCP", () => {
    it("liste les skills explicites", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary", {
            permission: { skill: { typescript: "allow" } },
          }),
        ],
        skills: [
          { name: "typescript", description: "TS", license: undefined, compatibility: undefined, metadata: {}, body: "" },
          { name: "docker", description: "Docker", license: undefined, compatibility: undefined, metadata: {}, body: "" },
        ],
      });
      const md = generateTeamSummary(snap);
      const buildBlock = md.slice(md.indexOf("### `build`"));
      const nextSection = buildBlock.indexOf("### `", 1);
      const block = nextSection > 0 ? buildBlock.slice(0, nextSection) : buildBlock;
      expect(block).toContain("Skills:");
      expect(block).toContain("`typescript`");
      expect(block).not.toContain("`docker`");
    });

    it("liste les MCP explicites", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary", {
            permission: { "github_*": { "*": "allow" } },
          }),
        ],
        mcps: [
          { name: "github", type: "remote", enabled: true, command: [], environment: {}, headers: {}, url: "http://localhost" },
        ],
      });
      const md = generateTeamSummary(snap);
      const buildBlock = md.slice(md.indexOf("### `build`"));
      const nextSection = buildBlock.indexOf("### `", 1);
      const block = nextSection > 0 ? buildBlock.slice(0, nextSection) : buildBlock;
      expect(block).toContain("MCP:");
      expect(block).toContain("`github`");
    });

    it("n'affiche pas Skills: none ni MCP: none", () => {
      const snap = baseSnapshot({
        agents: [makeAgent("build", "primary")],
        skills: [],
        mcps: [],
      });
      const md = generateTeamSummary(snap);
      expect(md).not.toContain("Skills: none");
      expect(md).not.toContain("MCP: none");
      expect(md).not.toContain("Delegates to: none");
    });
  });

  describe("état sans agent", () => {
    it("affiche un message quand aucun agent n'est configuré", () => {
      const snap = baseSnapshot({ agents: [] });
      const md = generateTeamSummary(snap);
      expect(md).toContain("No agents are currently configured.");
    });

    it("ne contient pas de sections ### quand il n'y a pas d'agents", () => {
      const snap = baseSnapshot({ agents: [] });
      const md = generateTeamSummary(snap);
      expect(md).not.toContain("### ");
    });
  });

  describe("absence d'informations sensibles", () => {
    it("n'inclut pas les permissions détaillées", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary", {
            permission: { edit: "allow", bash: "ask", read: "allow" },
          }),
        ],
      });
      const md = generateTeamSummary(snap);
      expect(md).not.toContain("edit");
      expect(md).not.toContain("bash");
      expect(md).not.toContain("read");
    });

    it("n'inclut pas les prompts", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary", { prompt: "You are a builder." }),
        ],
      });
      const md = generateTeamSummary(snap);
      expect(md).not.toContain("You are a builder");
    });

    it("n'inclut pas de secrets ni variables d'environnement", () => {
      const snap = baseSnapshot({
        mcps: [
          {
            name: "github",
            type: "remote",
            enabled: true,
            command: [],
            environment: { GITHUB_TOKEN: "secret123" },
            headers: {},
            url: "http://localhost",
          },
        ],
        agents: [makeAgent("build", "primary")],
      });
      const md = generateTeamSummary(snap);
      expect(md).not.toContain("secret123");
      expect(md).not.toContain("GITHUB_TOKEN");
    });
  });

  describe("ordre déterministe", () => {
    it("produit le même ordre à chaque appel", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("zebra", "subagent"),
          makeAgent("alpha", "subagent"),
          makeAgent("build", "primary"),
          makeAgent("plan", "primary"),
        ],
      });
      const md = generateTeamSummary(snap);
      const alphaIdx = md.indexOf("### `alpha`");
      const buildIdx = md.indexOf("### `build`");
      const planIdx = md.indexOf("### `plan`");
      const zebraIdx = md.indexOf("### `zebra`");
      expect(buildIdx).toBeLessThan(planIdx);
      expect(planIdx).toBeLessThan(alphaIdx);
      expect(alphaIdx).toBeLessThan(zebraIdx);
    });
  });

  describe("pas d'écriture de fichiers", () => {
    it("ne contient aucune référence à AGENTS.md", () => {
      const md = generateTeamSummary(baseSnapshot());
      expect(md).not.toContain("AGENTS.md");
    });

    it("est une fonction pure sans effets secondaires", () => {
      const snap = baseSnapshot();
      const before = JSON.stringify(snap);
      generateTeamSummary(snap);
      const after = JSON.stringify(snap);
      expect(before).toBe(after);
    });
  });

  describe("agents avec mode all", () => {
    it("place les agents 'all' entre primary et subagent", () => {
      const snap = baseSnapshot({
        agents: [
          makeAgent("build", "primary"),
          makeAgent("general", "all"),
          makeAgent("reviewer", "subagent"),
        ],
      });
      const md = generateTeamSummary(snap);
      const buildIdx = md.indexOf("### `build`");
      const generalIdx = md.indexOf("### `general`");
      const reviewerIdx = md.indexOf("### `reviewer`");
      expect(buildIdx).toBeLessThan(generalIdx);
      expect(generalIdx).toBeLessThan(reviewerIdx);
    });

    it("affiche le type correct pour mode all", () => {
      const snap = baseSnapshot({
        agents: [makeAgent("general", "all")],
      });
      const md = generateTeamSummary(snap);
      expect(md).toContain("- Type: all");
    });
  });
});
