import type { AgentDefinition, McpDefinition, SkillDefinition, TeamSnapshot } from "@/lib/types";

/**
 * Generate a short Markdown summary of the OpenCode team from a TeamSnapshot.
 *
 * Pure, deterministic, side-effect-free function.
 */
export function generateTeamSummary(snapshot: TeamSnapshot): string {
  const agents = snapshot.agents.filter((a) => !a.hidden);
  if (agents.length === 0) {
    return [
      "## OpenCode team",
      "",
      "No agents are currently configured.",
      "",
    ].join("\n");
  }

  const lines: string[] = [
    "## OpenCode team",
    "",
    "> Generated by OpenCode Team Studio from the current configuration.",
    "",
  ];

  const primaryAgents = agents.filter((a) => a.mode === "primary");
  const subAgentAgents = agents.filter((a) => a.mode === "subagent");
  const otherAgents = agents.filter((a) => a.mode === "all");

  const sorted = [
    ...primaryAgents.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: "base" })),
    ...otherAgents.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: "base" })),
    ...subAgentAgents.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: "base" })),
  ];

  const skillMap = new Map(snapshot.skills.map((s) => [s.name, s]));
  const mcpMap = new Map(snapshot.mcps.map((m) => [m.name, m]));

  for (const agent of sorted) {
    lines.push(...agentSummaryBlock(agent, snapshot, skillMap, mcpMap));
  }

  return lines.join("\n") + "\n";
}

function agentSummaryBlock(
  agent: AgentDefinition,
  snapshot: TeamSnapshot,
  skillMap: Map<string, SkillDefinition>,
  mcpMap: Map<string, McpDefinition>,
): string[] {
  const lines: string[] = [];

  lines.push(`### \`${agent.name}\``);
  lines.push("");

  const description = agent.description?.trim();
  if (description) {
    lines.push(description);
    lines.push("");
  }

  const typeLabel = agent.mode === "primary" ? "primary" : agent.mode === "all" ? "all" : "subagent";
  lines.push(`- Type: ${typeLabel}`);

  const sourceLabel = agent.builtin ? "builtin" : agent.source;
  lines.push(`- Source: ${sourceLabel}`);

  if (agent.model) {
    lines.push(`- Model: \`${agent.model}\``);
  }

  if (agent.variant) {
    lines.push(`- Variant: \`${agent.variant}\``);
  }

  if (agent.temperature !== undefined) {
    lines.push(`- Temperature: ${agent.temperature}`);
  }

  if (agent.top_p !== undefined) {
    lines.push(`- Top-p: ${agent.top_p}`);
  }

  if (agent.steps !== undefined) {
    lines.push(`- Steps: ${agent.steps}`);
  }

  if (agent.disable) {
    lines.push("- Disabled: true");
  }

  const delegates = getDelegatedAgents(agent, snapshot);
  if (delegates.length > 0) {
    lines.push(`- Delegates to: ${delegates.map((n) => `\`${n}\``).join(", ")}`);
  }

  const callers = getCallingAgents(agent, snapshot);
  if (callers.length > 0) {
    lines.push(`- Called by: ${callers.map((n) => `\`${n}\``).join(", ")}`);
  }

  const skills = getAgentSkills(agent, skillMap);
  if (skills.length > 0) {
    lines.push(`- Skills: ${skills.map((n) => `\`${n}\``).join(", ")}`);
  }

  const mcps = getAgentMcps(agent, mcpMap);
  if (mcps.length > 0) {
    lines.push(`- MCP: ${mcps.map((n) => `\`${n}\``).join(", ")}`);
  }

  lines.push("");
  return lines;
}

function getDelegatedAgents(agent: AgentDefinition, snapshot: TeamSnapshot): string[] {
  const delegated = new Set<string>();
  const taskPerms = agent.permission.task;
  if (typeof taskPerms === "string") {
    if (taskPerms === "allow") {
      for (const other of snapshot.agents) {
        if (other.name !== agent.name && other.mode !== "primary") {
          delegated.add(other.name);
        }
      }
    }
  } else if (typeof taskPerms === "object") {
    for (const [target, action] of Object.entries(taskPerms)) {
      if (action === "allow" || action === "ask") {
        delegated.add(target);
      }
    }
  }
  return [...delegated].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
}

function getCallingAgents(agent: AgentDefinition, snapshot: TeamSnapshot): string[] {
  const calledBy = new Set<string>();
  for (const other of snapshot.agents) {
    if (other.name === agent.name) continue;
    const taskPerms = other.permission.task;
    if (typeof taskPerms === "string") {
      if (taskPerms === "allow" && agent.mode !== "primary") {
        calledBy.add(other.name);
      }
    } else if (typeof taskPerms === "object") {
      if (taskPerms[agent.name] === "allow" || taskPerms[agent.name] === "ask") {
        calledBy.add(other.name);
      }
    }
  }
  return [...calledBy].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
}

function getAgentSkills(agent: AgentDefinition, skillMap: Map<string, SkillDefinition>): string[] {
  const skills = new Set<string>();
  const skillPerms = agent.permission.skill;
  if (typeof skillPerms === "string") {
    if (skillPerms === "allow") {
      for (const name of skillMap.keys()) {
        skills.add(name);
      }
    }
  } else if (typeof skillPerms === "object") {
    for (const [target, action] of Object.entries(skillPerms)) {
      if ((action === "allow" || action === "ask") && skillMap.has(target)) {
        skills.add(target);
      }
    }
  }
  return [...skills].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
}

function getAgentMcps(agent: AgentDefinition, mcpMap: Map<string, McpDefinition>): string[] {
  const mcps = new Set<string>();
  for (const [key, action] of Object.entries(agent.permission)) {
    if (key === "task" || key === "skill") continue;
    const mcpName = key.endsWith("_*") ? key.slice(0, -2) : null;
    if (mcpName && mcpMap.has(mcpName)) {
      if (typeof action === "string" && (action === "allow" || action === "ask")) {
        mcps.add(mcpName);
      } else if (typeof action === "object") {
        for (const v of Object.values(action)) {
          if (v === "allow" || v === "ask") {
            mcps.add(mcpName);
            break;
          }
        }
      }
    }
  }
  return [...mcps].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
}

