"use client";

import { BookOpen, Cable, Plus, Save, Server, Trash2, Wrench, X } from "lucide-react";
import { useState } from "react";
import { TypedObjectEditor } from "@/components/forms/typed-object-editor";
import { NATIVE_TOOLS } from "@/lib/team/permissions";
import type { McpDefinition, SkillDefinition, TeamSnapshot } from "@/lib/types";

type ResourceTab = "skills" | "mcp" | "tools";

export function ResourcesStudio({ initial }: { initial: TeamSnapshot }) {
  const [snapshot, setSnapshot] = useState(initial);
  const [tab, setTab] = useState<ResourceTab>("skills");
  const [skillDraft, setSkillDraft] = useState<SkillDefinition | null>(null);
  const [skillOriginal, setSkillOriginal] = useState<string | undefined>();
  const [mcpDraft, setMcpDraft] = useState<McpDefinition | null>(null);
  const [mcpOriginal, setMcpOriginal] = useState<string | undefined>();

  async function refresh() { const response = await fetch("/api/team", { cache: "no-store" }); if (response.ok) setSnapshot(await response.json()); }

  return <div className="content-page">
    <header className="page-header"><div><span className="eyebrow">Bibliothèque de l’équipe</span><h1>Ressources</h1><p>Gère les connaissances réutilisables, les outils externes et les capacités natives exposées aux agents.</p></div><div className="page-actions">{tab === "skills" ? <button className="button primary" onClick={() => { setSkillOriginal(undefined); setSkillDraft(emptySkill()); }}><Plus size={16} />Nouveau skill</button> : null}{tab === "mcp" ? <button className="button primary" onClick={() => { setMcpOriginal(undefined); setMcpDraft(emptyMcp()); }}><Plus size={16} />Nouveau MCP</button> : null}</div></header>
    <div className="segmented resource-tabs"><button className={tab === "skills" ? "active" : ""} onClick={() => setTab("skills")}><BookOpen size={15} />Skills</button><button className={tab === "mcp" ? "active" : ""} onClick={() => setTab("mcp")}><Cable size={15} />MCP</button><button className={tab === "tools" ? "active" : ""} onClick={() => setTab("tools")}><Wrench size={15} />Outils natifs</button></div>
    {tab === "skills" ? <SkillGrid skills={snapshot.skills} agents={snapshot.agents} onEdit={(skill) => { setSkillOriginal(skill.name); setSkillDraft(skill); }} /> : null}
    {tab === "mcp" ? <McpGrid mcps={snapshot.mcps} agents={snapshot.agents} onEdit={(mcp) => { setMcpOriginal(mcp.name); setMcpDraft(mcp); }} /> : null}
    {tab === "tools" ? <ToolGrid snapshot={snapshot} /> : null}
    {skillDraft ? <SkillEditor draft={skillDraft} original={skillOriginal} setDraft={setSkillDraft} onClose={() => setSkillDraft(null)} onSaved={async () => { setSkillDraft(null); await refresh(); }} /> : null}
    {mcpDraft ? <McpEditor draft={mcpDraft} original={mcpOriginal} setDraft={setMcpDraft} onClose={() => setMcpDraft(null)} onSaved={async () => { setMcpDraft(null); await refresh(); }} /> : null}
  </div>;
}

function SkillGrid({ skills, agents, onEdit }: { skills: SkillDefinition[]; agents: TeamSnapshot["agents"]; onEdit: (skill: SkillDefinition) => void }) {
  return <div className="resource-grid modern">{skills.map((skill) => { const users = agents.filter((agent) => permissionMentions(agent.permission.skill, skill.name)); return <button className="resource-tile" key={skill.name} onClick={() => onEdit(skill)}><div className="resource-tile-icon skill"><BookOpen size={20} /></div><div><span>SKILL</span><h2>{skill.name}</h2><p>{skill.description}</p></div><footer><b>{users.length} agent{users.length > 1 ? "s" : ""}</b><small>{skill.compatibility || "Compatibilité non précisée"}</small></footer></button>; })}{skills.length === 0 ? <Empty title="Aucun skill" text="Crée une procédure réutilisable, puis relie-la aux agents dans le graphe." /> : null}</div>;
}
function McpGrid({ mcps, agents, onEdit }: { mcps: McpDefinition[]; agents: TeamSnapshot["agents"]; onEdit: (mcp: McpDefinition) => void }) {
  return <div className="resource-grid modern">{mcps.map((mcp) => { const users = agents.filter((agent) => Boolean(agent.permission[`${mcp.name}_*`])); return <button className="resource-tile" key={mcp.name} onClick={() => onEdit(mcp)}><div className="resource-tile-icon mcp"><Server size={20} /></div><div><span>{mcp.type === "local" ? "MCP LOCAL" : mcp.type === "remote" ? "MCP DISTANT" : "RÉFÉRENCE MCP"}</span><h2>{mcp.name}</h2><p>{mcp.type === "local" ? mcp.command.join(" ") : mcp.url || "Serveur désactivé"}</p></div><footer><b>{users.length} agent{users.length > 1 ? "s" : ""}</b><small className={mcp.enabled ? "text-success" : "text-muted"}>{mcp.enabled ? "Activé" : "Désactivé"}</small></footer></button>; })}{mcps.length === 0 ? <Empty title="Aucun MCP" text="Ajoute un serveur d’outils local ou distant." /> : null}</div>;
}
function ToolGrid({ snapshot }: { snapshot: TeamSnapshot }) {
  return <div className="tool-catalog">{NATIVE_TOOLS.map((tool) => { const allow = snapshot.agents.filter((agent) => agent.permission[tool.id] === "allow").length; const ask = snapshot.agents.filter((agent) => agent.permission[tool.id] === "ask").length; return <article className="tool-card" key={tool.id}><div className="resource-tile-icon tool"><Wrench size={18} /></div><div><span>OUTIL NATIF</span><h3>{tool.label}</h3><p>{tool.description}</p></div><footer><b>{allow} autorisés</b><small>{ask} avec confirmation</small></footer></article>; })}</div>;
}

function SkillEditor({ draft, original, setDraft, onClose, onSaved }: { draft: SkillDefinition; original?: string; setDraft: (value: SkillDefinition) => void; onClose: () => void; onSaved: () => void }) {
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); setError(""); try { const response = await fetch(original ? `/api/resources/skills/${encodeURIComponent(original)}` : "/api/resources/skills", { method: original ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); onSaved(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Erreur inconnue"); } finally { setSaving(false); } }
  async function remove() { if (!original || !window.confirm(`Supprimer ${original} ?`)) return; await fetch(`/api/resources/skills/${encodeURIComponent(original)}`, { method: "DELETE" }); onSaved(); }
  return <Drawer title={original ? draft.name : "Nouveau skill"} subtitle="Connaissance réutilisable" onClose={onClose}><div className="drawer-form"><Field label="Nom"><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="Description"><textarea rows={3} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></Field><div className="two-fields"><Field label="Licence"><input value={draft.license || ""} onChange={(event) => setDraft({ ...draft, license: event.target.value || undefined })} /></Field><Field label="Compatibilité"><input value={draft.compatibility || ""} onChange={(event) => setDraft({ ...draft, compatibility: event.target.value || undefined })} /></Field></div><TypedObjectEditor title="Métadonnées" value={draft.metadata} onChange={(value) => setDraft({ ...draft, metadata: Object.fromEntries(Object.entries(value).map(([key, item]) => [key, String(item)])) })} /><Field label="Contenu du skill"><textarea className="prompt-editor short" value={draft.body} onChange={(event) => setDraft({ ...draft, body: event.target.value })} /></Field>{error ? <div className="inline-message error">{error}</div> : null}</div><DrawerFooter>{original ? <button className="button danger-outline" onClick={remove}><Trash2 size={15} />Supprimer</button> : <span />}<button className="button primary" onClick={save} disabled={saving || !draft.name || !draft.description}><Save size={15} />Enregistrer</button></DrawerFooter></Drawer>;
}

function McpEditor({ draft, original, setDraft, onClose, onSaved }: { draft: McpDefinition; original?: string; setDraft: (value: McpDefinition) => void; onClose: () => void; onSaved: () => void }) {
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); setError(""); try { const response = await fetch(original ? `/api/resources/mcp/${encodeURIComponent(original)}` : "/api/resources/mcp", { method: original ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); onSaved(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Erreur inconnue"); } finally { setSaving(false); } }
  async function remove() { if (!original || !window.confirm(`Supprimer ${original} ?`)) return; await fetch(`/api/resources/mcp/${encodeURIComponent(original)}`, { method: "DELETE" }); onSaved(); }
  return <Drawer title={original ? draft.name : "Nouveau MCP"} subtitle="Serveur d’outils OpenCode" onClose={onClose}><div className="drawer-form"><Field label="Nom"><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><div className="two-fields"><Field label="Type"><select value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value as McpDefinition["type"] })}><option value="local">Local</option><option value="remote">Distant</option><option value="disabled">Référence désactivée</option></select></Field><label className="toggle-line compact"><input type="checkbox" checked={draft.enabled} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })} /><span><strong>Activé</strong><small>Chargé au démarrage</small></span></label></div>{draft.type === "local" ? <><Field label="Commande" hint="Un argument par ligne"><textarea rows={5} value={draft.command.join("\n")} onChange={(event) => setDraft({ ...draft, command: event.target.value.split("\n").filter(Boolean) })} /></Field><Field label="Dossier de travail"><input value={draft.cwd || ""} onChange={(event) => setDraft({ ...draft, cwd: event.target.value || undefined })} /></Field><TypedObjectEditor title="Variables d’environnement" value={draft.environment} onChange={(value) => setDraft({ ...draft, environment: stringMap(value) })} /></> : null}{draft.type === "remote" ? <><Field label="URL"><input value={draft.url || ""} onChange={(event) => setDraft({ ...draft, url: event.target.value })} /></Field><TypedObjectEditor title="En-têtes HTTP" value={draft.headers} onChange={(value) => setDraft({ ...draft, headers: stringMap(value) })} /></> : null}{draft.type !== "disabled" ? <Field label="Timeout (ms)"><input type="number" value={draft.timeout ?? ""} onChange={(event) => setDraft({ ...draft, timeout: event.target.value ? Number(event.target.value) : undefined })} /></Field> : null}{error ? <div className="inline-message error">{error}</div> : null}</div><DrawerFooter>{original ? <button className="button danger-outline" onClick={remove}><Trash2 size={15} />Supprimer</button> : <span />}<button className="button primary" onClick={save} disabled={saving || !draft.name}><Save size={15} />Enregistrer</button></DrawerFooter></Drawer>;
}

function Drawer({ title, subtitle, onClose, children }: { title: string; subtitle: string; onClose: () => void; children: React.ReactNode }) { return <div className="drawer-backdrop" onMouseDown={(event) => event.currentTarget === event.target && onClose()}><aside className="resource-drawer"><header><div><span>{subtitle}</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={18} /></button></header>{children}</aside></div>; }
function DrawerFooter({ children }: { children: React.ReactNode }) { return <footer className="drawer-footer">{children}</footer>; }
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="field"><span>{label}{hint ? <small>{hint}</small> : null}</span>{children}</label>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty-state"><Plus size={25} /><h3>{title}</h3><p>{text}</p></div>; }
function emptySkill(): SkillDefinition { return { name: "", description: "", metadata: {}, body: "## Objectif\n\nDécris ici les connaissances et procédures réutilisables.\n" }; }
function emptyMcp(): McpDefinition { return { name: "", type: "local", enabled: true, command: ["npx", "-y"], environment: {}, headers: {} }; }
function stringMap(value: Record<string, unknown>) { return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, String(item)])); }
function permissionMentions(value: unknown, target: string) { if (typeof value === "string") return value !== "deny"; if (!value || typeof value !== "object" || Array.isArray(value)) return false; return Object.keys(value).some((pattern) => pattern === target || pattern === "*" || pattern.includes("*")); }
